name: lint
on:
  push:
    branches:
      - main
    paths:
      - "**.yaml"
      - "**.toml"
  pull_request:
    branches:
      - main
    paths:
      - "**.yaml"
      - "**.toml"

permissions: {}

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
        with:
          version: 2024.12.24
          install_args: "npm:prettier"
      - name: prettier
        run: prettier --check '**/*.{yaml,yml}'

  lint-toml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
        with:
          version: 2024.12.24
          install_args: "npm:@taplo/cli"
      - name: taplo
        run: taplo format --check
